/**
 * Corpus for the golden TEXT/COMMENT parity harness (Stage 0).
 *
 * Each case id maps to a committed golden file
 * test/unit/parity/__golden__/text/<id>.json regenerated by
 * scripts/parity/regen-text-goldens.mjs (run with bun).
 *
 * Inputs deliberately pin quirks listed in docs/langium-migration/07-risk-map.md
 * ("Port verbatim" list) and the G4 comment-attachment semantics.
 */
export interface TextCorpusCase {
  id: string;
  description: string;
  code: string;
}

export const textCorpus: TextCorpusCase[] = [
  {
    id: "comment-multiline-before-statement",
    description:
      "Multiple consecutive // comment lines attach to the following statement, joined with \\n",
    code: "// first line\n// second line\nA.method()",
  },
  {
    id: "comment-styled-directive",
    description:
      "Styling directive comment '// [bold,#red] styled' drives messageStyle downstream",
    code: "// [bold,#red] styled\nA->B: hi",
  },
  {
    id: "comment-before-closing-brace",
    description:
      "BraceBlockContext.getComment() reads the comment left of the closing '}' (stop token special case)",
    code: "A.method() { // comment \n }",
  },
  {
    id: "comment-between-statements",
    description: "Comment between two statements attaches to the second one",
    code: "A.m1()\n// between\nB.m2()",
  },
  {
    id: "comment-indented-leading-spaces",
    description:
      "Indented comments: leading spaces after // must be preserved; comment line itself indented",
    code: "//   three leading spaces\n  // indented comment line\nA.m",
  },
  {
    id: "divider-comma-quirk",
    description:
      "Divider '==A, B==' — pinned quirk: note text flattens to 'A,B' (comma loses trailing space)",
    code: "==A, B==",
  },
  {
    id: "async-message-leading-space-signature",
    description:
      "Async message content after ':' keeps the leading space in the raw payload token",
    code: "A->B: message",
  },
  {
    id: "self-message-with-brace-block",
    description: "Self message keeps parens; nested self() inside brace block",
    code: "A.m() { self() }",
  },
  {
    id: "method-chain-flattening",
    description: "A.m1.m2 — signature flattens the dotted chain to 'm1.m2'",
    code: "A.m1.m2",
  },
  {
    id: "creation-with-create-guillemets",
    description:
      "Creation statement — downstream renders «create»; golden pins text facets of creation/parameters",
    code: "a = new A(1, 2)",
  },
  {
    id: "quoted-participant-names",
    description:
      "Quoted participant names: getFormattedText strips one pair of quotes, getText keeps them",
    code: '"Alice Smith"\n"Alice Smith"->Bob: hello',
  },
  {
    id: "parameters-named",
    description:
      "Named parameters — ParametersContext.getFormattedText override (per-kind override contract)",
    code: "A.m(a=1, b=2)",
  },
  {
    id: "parameters-trailing-comma",
    description: "Trailing comma tolerance 'm(a,)' (tolerance point 18)",
    code: "A.m(a,)",
  },
  {
    id: "chinese-text",
    description: "CJK participant/method/parameter names and async payload",
    code: "用户.登录(密码)\n用户->系统: 你好",
  },
  {
    id: "emoji",
    description: "Emoji in async payload and in a comment",
    code: "// 😀 emoji comment\nUser->Bob: hi 🎉",
  },
];
