// Common emoji shortcodes used in technical communication.
// This is a curated subset — not an exhaustive list.
const EMOJI_MAP: Record<string, string> = {
  // People & Faces
  smile: "😄",
  laughing: "😆",
  blush: "😊",
  smiley: "😃",
  relaxed: "☺️",
  wink: "😉",
  heart_eyes: "😍",
  kissing_heart: "😘",
  stuck_out_tongue_winking_eye: "😜",
  stuck_out_tongue: "😛",
  sunglasses: "😎",
  smirk: "😏",
  unamused: "😒",
  disappointed: "😞",
  cry: "😢",
  sob: "😭",
  joy: "😂",
  astonished: "😲",
  scream: "😱",
  rage: "😡",
  thinking: "🤔",
  shrug: "🤷",
  facepalm: "🤦",
  clown: "🤡",
  ghost: "👻",
  skull: "💀",
  robot: "🤖",

  // Gestures
  thumbsup: "👍",
  "+1": "👍",
  thumbsdown: "👎",
  "-1": "👎",
  ok_hand: "👌",
  wave: "👋",
  clap: "👏",
  muscle: "💪",
  pray: "🙏",
  point_up: "☝️",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  raised_hands: "🙌",

  // Hearts & Symbols
  heart: "❤️",
  broken_heart: "💔",
  star: "⭐",
  sparkles: "✨",
  zap: "⚡",
  fire: "🔥",
  boom: "💥",
  100: "💯",
  check: "✅",
  white_check_mark: "✅",
  x: "❌",
  warning: "⚠️",
  no_entry: "🚫",
  question: "❓",
  exclamation: "❗",
  bell: "🔔",
  megaphone: "📣",

  // Objects & Tech
  computer: "💻",
  keyboard: "⌨️",
  email: "📧",
  envelope: "✉️",
  phone: "📱",
  gear: "⚙️",
  wrench: "🔧",
  hammer: "🔨",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  bulb: "💡",
  mag: "🔍",
  link: "🔗",
  paperclip: "📎",
  clipboard: "📋",
  memo: "📝",
  book: "📖",
  calendar: "📅",
  clock: "🕐",
  hourglass: "⏳",
  package: "📦",
  gift: "🎁",
  trophy: "🏆",
  medal: "🏅",
  medal_sports: "🏅",
  flag: "🚩",
  rocket: "🚀",
  airplane: "✈️",
  car: "🚗",
  truck: "🚚",
  ship: "🚢",

  // Nature & Animals
  unicorn: "🦄",
  dog: "🐶",
  cat: "🐱",
  mouse: "🐭",
  rabbit: "🐰",
  bear: "🐻",
  panda: "🐼",
  penguin: "🐧",
  bird: "🐦",
  butterfly: "🦋",
  bug: "🐛",
  bee: "🐝",
  snake: "🐍",
  turtle: "🐢",
  fish: "🐟",
  octopus: "🐙",
  whale: "🐳",
  dolphin: "🐬",
  dragon: "🐉",
  sun: "☀️",
  moon: "🌙",
  cloud: "☁️",
  rainbow: "🌈",
  snowflake: "❄️",
  tree: "🌳",
  flower: "🌸",
  rose: "🌹",
  cactus: "🌵",

  // Food & Drink
  coffee: "☕",
  beer: "🍺",
  pizza: "🍕",
  apple: "🍎",
  cake: "🎂",
  cookie: "🍪",
  icecream: "🍦",

  // Arrows & UI
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  arrow_left: "⬅️",
  arrow_right: "➡️",
  arrows_counterclockwise: "🔄",
  heavy_plus_sign: "➕",
  heavy_minus_sign: "➖",
  heavy_multiplication_x: "✖️",
  heavy_division_sign: "➗",
  infinity: "♾️",
  recycle: "♻️",
  info: "ℹ️",

  // Status & indicators
  green_circle: "🟢",
  red_circle: "🔴",
  yellow_circle: "🟡",
  blue_circle: "🔵",
  white_circle: "⚪",
  black_circle: "⚫",
};

const SHORTCODE_REGEX = /:([a-zA-Z0-9_+-]+):/g;

/**
 * Convert emoji shortcodes like :unicorn: to their emoji characters.
 * Unknown shortcodes are left as-is.
 */
export function convertEmojiShortcodes(text: string): string {
  return text.replace(SHORTCODE_REGEX, (match, code) => {
    return EMOJI_MAP[code] ?? match;
  });
}
