name: Update Playwright Snapshots for Linux

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-snapshots:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Build site
        run: pnpm build:site

      - name: Generate Linux snapshots
        run: pnpm pw:update-ci
        env:
          CI: true

      - name: Commit updated snapshots
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tests/
          if ! git diff --staged --quiet; then
            git commit -m "chore: update Playwright snapshots for Linux CI

            Generated Linux-specific snapshots for chromium-linux platform.
            
            🤖 Generated with [Claude Code](https://claude.ai/code)
            
            Co-Authored-By: Claude <noreply@anthropic.com>"
            git push
          else
            echo "No snapshot changes to commit"
          fi
